language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"

matrix:
   allow_failures:
      - perl: "5.8"

before_install:
   # git bits sometimes needed...
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'

install:
   # not so much install our package as all its prereqs
   - cpanm --installdeps . || { cat ~/.cpanm/build.log ; false ; }

script:
   - perl Makefile.PL
   - make test
